/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 1600x800x400.gltf --transform 
Files: 1600x800x400.gltf [6.46KB] > C:\Users\Hampu\OneDrive\Dokument\GitHub\ByggKlossProjekt\src\assets\1600x800x400-transformed.glb [4.9KB] (24%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/1600x800x400-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['800x800x400'].geometry} material={nodes['800x800x400'].material} position={[-4, 0, 0]} scale={[0.4, 1, 0.4]} />
    </group>
  )
}

useGLTF.preload('/1600x800x400-transformed.glb')
