/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 agab_block_1600x800x800.gltf --transform 
Files: agab_block_1600x800x800.gltf [1.64KB] > C:\Users\Hampu\OneDrive\Dokument\GitHub\ByggKlossProjekt\src\assets\agab_block_1600x800x800-transformed.glb [4.34KB] (-165%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/agab_block_1600x800x800-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[-0.133, 0.027, 0.041]} scale={[0.8, 1, 0.4]} />
    </group>
  )
}

useGLTF.preload('/agab_block_1600x800x800-transformed.glb')
