/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 agab_block_800x400x400.gltf --transform 
Files: agab_block_800x400x400.gltf [1.39KB] > C:\Users\Hampu\OneDrive\Dokument\GitHub\ByggKlossProjekt\src\assets\agab_block_800x400x400-transformed.glb [1.8KB] (-29%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/agab_block_800x400x400-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['800x400x400'].geometry} material={nodes['800x400x400'].material} />
    </group>
  )
}

useGLTF.preload('/agab_block_800x400x400-transformed.glb')
